<?php
/**
 * Email Marketing Component - Configuration File Template
 * Copy this file to config.php during installation
 * DO NOT EDIT THIS FILE - Edit config.php instead
 */

// Component version
define('EMAIL_MARKETING_VERSION', '1.0.0');

// Installation timestamp
define('EMAIL_MARKETING_INSTALLED_AT', '');

// Database configuration
define('EMAIL_MARKETING_DB_HOST', '');
define('EMAIL_MARKETING_DB_USER', '');
define('EMAIL_MARKETING_DB_PASS', '');
define('EMAIL_MARKETING_DB_NAME', '');

// Path configuration
define('EMAIL_MARKETING_ROOT_PATH', '');
define('EMAIL_MARKETING_ADMIN_PATH', '');

// URL configuration
define('EMAIL_MARKETING_BASE_URL', '');
define('EMAIL_MARKETING_ADMIN_URL', '');

// Base system information (JSON)
define('EMAIL_MARKETING_BASE_SYSTEM_INFO', '{}');

// Email sending configuration
define('EMAIL_MARKETING_EMAIL_METHOD', 'smtp'); // 'smtp' or 'service'
define('EMAIL_MARKETING_SMTP_HOST', '');
define('EMAIL_MARKETING_SMTP_PORT', '587');
define('EMAIL_MARKETING_SMTP_ENCRYPTION', 'tls'); // 'tls' or 'ssl'
define('EMAIL_MARKETING_SMTP_USERNAME', '');
define('EMAIL_MARKETING_SMTP_PASSWORD', '');
define('EMAIL_MARKETING_FROM_EMAIL', '');
define('EMAIL_MARKETING_FROM_NAME', '');

// Service provider configuration (if using service method)
define('EMAIL_MARKETING_SERVICE_PROVIDER', ''); // 'sendgrid', 'mailgun', 'ses'
define('EMAIL_MARKETING_SERVICE_API_KEY', '');

// Queue processing
define('EMAIL_MARKETING_QUEUE_ENABLED', true);
define('EMAIL_MARKETING_QUEUE_BATCH_SIZE', 50);

// Rate limiting
define('EMAIL_MARKETING_RATE_LIMIT_PER_HOUR', 1000);

